
-- StockSense PostgreSQL schema
-- Apply to a fresh database before running seed.sql.
BEGIN;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (btrim(name) <> ''),
  email TEXT NOT NULL CHECK (btrim(email) <> ''),
  password_hash TEXT NOT NULL CHECK (btrim(password_hash) <> ''),
  role TEXT NOT NULL DEFAULT 'STAFF' CHECK (role IN ('ADMIN', 'STAFF')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT users_email_unique UNIQUE (email)
);
CREATE UNIQUE INDEX users_email_ci_unique ON users (lower(email));

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE CHECK (btrim(name) <> ''),
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE warehouses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (btrim(name) <> ''),
  code TEXT NOT NULL UNIQUE CHECK (btrim(code) <> ''),
  address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id BIGINT NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
  name TEXT NOT NULL CHECK (btrim(name) <> ''),
  code TEXT NOT NULL CHECK (btrim(code) <> ''),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (warehouse_id, code),
  UNIQUE (id, warehouse_id)
);
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (btrim(name) <> ''),
  sku TEXT NOT NULL UNIQUE CHECK (btrim(sku) <> ''),
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  unit_of_measure TEXT NOT NULL CHECK (btrim(unit_of_measure) <> ''),
  reorder_level NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE stock (
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (product_id, location_id)
);

CREATE TABLE receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_number TEXT NOT NULL UNIQUE CHECK (btrim(document_number) <> ''),
  warehouse_id BIGINT NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
  supplier_name TEXT NOT NULL CHECK (btrim(supplier_name) <> ''),
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'VALIDATED', 'CANCELLED')),
  notes TEXT,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  validated_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  validated_at TIMESTAMPTZ,
  CHECK ((status = 'VALIDATED' AND validated_at IS NOT NULL AND validated_by IS NOT NULL)
      OR (status IN ('DRAFT', 'CANCELLED') AND validated_at IS NULL AND validated_by IS NULL))
);
CREATE TABLE receipt_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id BIGINT NOT NULL REFERENCES receipts(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  quantity NUMERIC(18,3) NOT NULL CHECK (quantity > 0),
  unit_of_measure TEXT NOT NULL CHECK (btrim(unit_of_measure) <> ''),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (receipt_id, product_id, location_id)
);
CREATE TABLE deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_number TEXT NOT NULL UNIQUE CHECK (btrim(document_number) <> ''),
  warehouse_id BIGINT NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
  customer_name TEXT NOT NULL CHECK (btrim(customer_name) <> ''),
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'VALIDATED', 'CANCELLED')),
  notes TEXT,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  validated_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  validated_at TIMESTAMPTZ,
  CHECK ((status = 'VALIDATED' AND validated_at IS NOT NULL AND validated_by IS NOT NULL)
      OR (status IN ('DRAFT', 'CANCELLED') AND validated_at IS NULL AND validated_by IS NULL))
);
CREATE TABLE delivery_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delivery_id BIGINT NOT NULL REFERENCES deliveries(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  quantity NUMERIC(18,3) NOT NULL CHECK (quantity > 0),
  unit_of_measure TEXT NOT NULL CHECK (btrim(unit_of_measure) <> ''),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (delivery_id, product_id, location_id)
);
CREATE TABLE transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_number TEXT NOT NULL UNIQUE CHECK (btrim(document_number) <> ''),
  source_location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  destination_location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'VALIDATED', 'CANCELLED')),
  notes TEXT,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  validated_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  validated_at TIMESTAMPTZ,
  CHECK (source_location_id <> destination_location_id),
  CHECK ((status = 'VALIDATED' AND validated_at IS NOT NULL AND validated_by IS NOT NULL)
      OR (status IN ('DRAFT', 'CANCELLED') AND validated_at IS NULL AND validated_by IS NULL))
);
CREATE TABLE transfer_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id BIGINT NOT NULL REFERENCES transfers(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity NUMERIC(18,3) NOT NULL CHECK (quantity > 0),
  unit_of_measure TEXT NOT NULL CHECK (btrim(unit_of_measure) <> ''),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (transfer_id, product_id)
);
CREATE TABLE adjustments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_number TEXT NOT NULL UNIQUE CHECK (btrim(document_number) <> ''),
  warehouse_id BIGINT NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'VALIDATED', 'CANCELLED')),
  reason TEXT NOT NULL CHECK (btrim(reason) <> ''),
  notes TEXT,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  validated_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  validated_at TIMESTAMPTZ,
  CHECK ((status = 'VALIDATED' AND validated_at IS NOT NULL AND validated_by IS NOT NULL)
      OR (status IN ('DRAFT', 'CANCELLED') AND validated_at IS NULL AND validated_by IS NULL))
);
CREATE TABLE adjustment_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  adjustment_id BIGINT NOT NULL REFERENCES adjustments(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  physical_quantity NUMERIC(18,3) NOT NULL CHECK (physical_quantity >= 0),
  unit_of_measure TEXT NOT NULL CHECK (btrim(unit_of_measure) <> ''),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (adjustment_id, product_id, location_id)
);
CREATE TABLE stock_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
  movement_type TEXT NOT NULL CHECK (movement_type IN ('RECEIPT', 'DELIVERY', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT')),
  quantity NUMERIC(18,3) NOT NULL CHECK (quantity <> 0),
  reference_type TEXT NOT NULL CHECK (reference_type IN ('RECEIPT', 'DELIVERY', 'TRANSFER', 'ADJUSTMENT')),
  -- No polymorphic FK: reference_id points to the document table named by reference_type.
  reference_id BIGINT NOT NULL CHECK (reference_id >= 0),
  notes TEXT,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK ((movement_type IN ('RECEIPT', 'TRANSFER_IN') AND quantity > 0)
      OR (movement_type IN ('DELIVERY', 'TRANSFER_OUT') AND quantity < 0)
      OR movement_type = 'ADJUSTMENT'),
  CHECK ((movement_type = 'RECEIPT' AND reference_type = 'RECEIPT')
      OR (movement_type = 'DELIVERY' AND reference_type = 'DELIVERY')
      OR (movement_type IN ('TRANSFER_IN', 'TRANSFER_OUT') AND reference_type = 'TRANSFER')
      OR (movement_type = 'ADJUSTMENT' AND reference_type = 'ADJUSTMENT'))
);
CREATE TABLE password_reset_otps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  otp_hash TEXT NOT NULL CHECK (btrim(otp_hash) <> ''),
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX locations_warehouse_id_idx ON locations (warehouse_id);
CREATE INDEX products_category_id_idx ON products (category_id);
CREATE INDEX stock_location_id_idx ON stock (location_id);
CREATE INDEX receipts_status_created_idx ON receipts (status, created_at DESC);
CREATE INDEX deliveries_status_created_idx ON deliveries (status, created_at DESC);
CREATE INDEX transfers_status_created_idx ON transfers (status, created_at DESC);
CREATE INDEX adjustments_status_created_idx ON adjustments (status, created_at DESC);
CREATE INDEX receipt_items_product_idx ON receipt_items (product_id);
CREATE INDEX delivery_items_product_idx ON delivery_items (product_id);
CREATE INDEX transfer_items_product_idx ON transfer_items (product_id);
CREATE INDEX adjustment_items_product_idx ON adjustment_items (product_id);
CREATE INDEX stock_ledger_product_created_idx ON stock_ledger (product_id, created_at DESC, id DESC);
CREATE INDEX stock_ledger_location_created_idx ON stock_ledger (location_id, created_at DESC, id DESC);
CREATE INDEX stock_ledger_reference_idx ON stock_ledger (reference_type, reference_id);
CREATE INDEX password_reset_otps_user_expiry_idx ON password_reset_otps (user_id, expires_at DESC);

COMMIT;


